#!/usr/bin/env python3
"""
Script to aggregate all turtle (.ttl) files in a directory and its subdirectories.
This script finds all .ttl files recursively and combines them into a single output file.
"""

import os
import sys
from pathlib import Path

def find_ttl_files(directory):
    """
    Find all .ttl files recursively in the given directory.
    
    Args:
        directory (str): The directory to search for .ttl files
        
    Returns:
        list: A list of paths to .ttl files
    """
    ttl_files = []
    directory_path = Path(directory)
    
    # Use rglob to recursively find all .ttl files
    for ttl_file in directory_path.rglob("*.ttl"):
        # Skip the output file if it's in the same directory (to avoid infinite recursion)
        if ttl_file.name == "aggregated_vocab.ttl":
            continue
        ttl_files.append(ttl_file)
    
    return ttl_files

def aggregate_ttl_files(ttl_files, output_file):
    """
    Aggregate all turtle files into a single output file.
    
    Args:
        ttl_files (list): List of paths to .ttl files
        output_file (str): Path to the output file
    """
    print(f"Aggregating {len(ttl_files)} turtle files...")
    
    with open(output_file, 'w') as outfile:
        # Add a header to the output file
        outfile.write("# Aggregated Turtle Vocabulary\n")
        outfile.write("# Generated by aggregate_turtle.py\n")
        outfile.write("#\n")
        
        for ttl_file in ttl_files:
            print(f"  Processing: {ttl_file}")
            try:
                with open(ttl_file, 'r') as infile:
                    # Read the content of the current file
                    content = infile.read()
                    # Add a comment indicating the source file
                    outfile.write(f"\n# === Content from {ttl_file} ===\n")
                    outfile.write(content)
                    # Add a blank line after each file for readability
                    outfile.write("\n")
            except Exception as e:
                print(f"  Error reading {ttl_file}: {e}")
                # Continue with other files even if one fails
                continue
    
    print(f"Aggregation complete. Output saved to {output_file}")

def main():
    """
    Main function to run the aggregation script.
    """
    # Default directory is the current directory
    directory = "data"
    output_file = "aggregated-raid-skos.ttl"
    
    # Check if directory argument is provided
    if len(sys.argv) > 1:
        directory = sys.argv[1]
    
    # Check if output file argument is provided
    if len(sys.argv) > 2:
        output_file = sys.argv[2]
    
    # Validate that the directory exists
    if not os.path.exists(directory):
        print(f"Error: Directory '{directory}' does not exist.")
        sys.exit(1)
    
    # Find all .ttl files
    ttl_files = find_ttl_files(directory)
    
    if not ttl_files:
        print("No .ttl files found in the directory.")
        return
    
    # Sort the files for consistent output
    ttl_files.sort()
    
    # Aggregate the files
    aggregate_ttl_files(ttl_files, output_file)
    
    print(f"Successfully aggregated {len(ttl_files)} turtle files into {output_file}")

if __name__ == "__main__":
    main()